default_language_version:
  python: python3.9

repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.0.0
        hooks:
        -   id: check-ast
        -   id: trailing-whitespace
            files: (.*\.py$|.*\.yml$)
        -   id: check-merge-conflict
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: mixed-line-ending
        -   id: no-commit-to-branch

    -   repo: https://github.com/jendrikseipp/vulture
        rev: v2.3
        hooks:
        -   id: vulture

    -   repo: https://github.com/pycqa/isort
        rev: 5.6.4
        hooks:
        -   id: isort

    -   repo: https://github.com/psf/black
        rev: 21.9b0
        hooks:
        -   id: black

    -   repo: https://gitlab.com/pycqa/flake8
        rev: 3.8.3
        hooks:
        -   id: flake8

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.782
        hooks:
        -   id: mypy

    -   repo: https://github.com/econchick/interrogate
        rev: 1.5.0
        hooks:
        -   id: interrogate

    -   repo: https://github.com/commitizen-tools/commitizen
        rev: v2.20.0
        hooks:
        -   id: commitizen
            stages: [commit-msg]
