name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      
      - name: Install poetry and app dependencies
        run: poetry export --dev --without-hashes --format requirements.txt | pip install --no-cache-dir -r /dev/stdin
      
      - name: Testing
        run: |
          pytest
